[features]
seeds = false
skip-lint = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "programs/sallar/tests/fixtures/mpl_token_metadata.so"

[programs.localnet]
sallar = "ALLdaozmHS1MTT2dMtVUW6LUbDeJGNAMAxU8q9wN6Nny"
[programs.devnet]
sallar = "ALLdaozmHS1MTT2dMtVUW6LUbDeJGNAMAxU8q9wN6Nny"
[programs.testnet]
sallar = "ALLdaozmHS1MTT2dMtVUW6LUbDeJGNAMAxU8q9wN6Nny"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/basic/*.ts"
allTests = "sh scripts/run-anchor-tests.sh basicTests userRestTests"
basicTests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/basic/*.ts"
userRestTests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/user-rest/*.ts"
